import { createAlgorithm } from '../phonetic/algorithm.ts';

const sh = 'X';
const th = '0';

const VOWEL = ['A', 'E', 'I', 'O', 'U'];
const DIPHTHONG = ['C', 'G', 'P', 'S', 'T'];
const SOFT = ['E', 'I', 'Y'];

// prettier-ignore
export const algorithm = createAlgorithm({
  forking: false,
  keep: { alphabetic: true, whitespace: true },
  // priorRules: [
  //   { r: /([BDH]..)GH/gv, s: '$1-'  },
  //   { r: /(H...)GH/gv,    s: '$1-'  },
  //   { r: /GN(-| |$)/gv,   s: 'N'    },
  // ],
  removeDuplicates: 'metaphone',
  padding: true,
  scan: [
    { m: 'AE',  i: 'b',                                   o: 'E'  },
    { m: 'A',   i: 'b',                                   o: 'A'  },
    { m: 'A',                                             o: '-'  },
    { m: 'B',                               ṗ: 'M',       o: 'B'  },
    { m: 'B',                                             o: '-'  },
    { m: 'CIA',                                           o: sh   },
    { m: 'C',           n: SOFT,            ṗ: 'S',       o: 'S'  },
    { m: 'C',           n: SOFT,                          o: '-'  },
    { m: 'CH',                                            o: sh   },
    { m: 'C',                                             o: 'K'  },
    { m: 'DG',          n: SOFT,                          o: 'J'  },
    { m: 'D',                                             o: 'T'  },
    { m: 'E',   i: 'b',                                   o: 'E'  },
    { m: 'E',                                             o: '-'  },
    { m: 'F',                                             o: 'F'  },
    { m: 'GH',          p2: ['B', 'D', 'H'],              o: '-'  },
    { m: 'GH',          p3: 'H',                          o: '-'  },
    { m: 'GH',                                            o: 'F'  },
    { m: 'GN',  i: 'b',                                   o: 'N'  },
    { m: 'G',           n: ['N ', 'NED'],                 o: '-'  },
    { m: 'G',           n: SOFT,            ṗ: 'G',       o: 'J'  },
    { m: 'G',                                             o: 'K'  },
    { m: 'H',           n: VOWEL,           ṗ: DIPHTHONG, o: 'H'  },
    { m: 'H',                                             o: '-'  },
    { m: 'I',   i: 'b',                                   o: 'I'  },
    { m: 'I',                                             o: '-'  },
    { m: 'J',                                             o: 'J'  },
    { m: 'KN',  i: 'b',                                   o: 'N'  },
    { m: 'K',                               ṗ: 'C',       o: 'K'  },
    { m: 'K',                                             o: '-'  },
    { m: 'L',                                             o: 'L'  },
    { m: 'M',                                             o: 'M'  },
    { m: 'N',                                             o: 'N'  },
    { m: 'O',   i: 'b',                                   o: 'O'  },
    { m: 'O',                                             o: '-'  },
    { m: 'PN',  i: 'b',                                   o: 'N'  },
    { m: 'P',             n: 'H',                         o: 'F'  },
    { m: 'P',                                             o: 'P'  },
    { m: 'Q',                                             o: 'K'  },
    { m: 'R',                                             o: 'R'  },
    { m: 'S',             n: ['IO', 'IA'],                o: sh   },
    { m: 'SH',                                            o: sh   },
    { m: 'S',                                             o: 'S'  },
    { m: 'T',             n: ['IO', 'IA'],                o: sh   },
    { m: 'TH',                                            o: th   },
    { m: 'T',             ṅ: 'CH',                        o: 'T'  },
    { m: 'T',                                             o: '-'  },
    { m: 'U',   i: 'b',                                   o: 'U'  },
    { m: 'U',                                             o: '-'  },
    { m: 'V',                                             o: 'F'  },
    { m: 'WR',  i: 'b',                                   o: 'R'  },
    { m: 'WH',  i: 'b',                                   o: 'W'  },
    { m: 'WA',  i: 'b',                                   o: 'W'  },
    { m: 'WE',  i: 'b',                                   o: 'W'  },
    { m: 'WI',  i: 'b',                                   o: 'W'  },
    { m: 'WO',  i: 'b',                                   o: 'W'  },
    { m: 'WU',  i: 'b',                                   o: 'W'  },
    { m: 'W',             n: VOWEL,                       o: 'W'  },
    { m: 'W',                                             o: '-'  },
    { m: 'X',   i: 'b',                                   o: 'S'  },
    { m: 'X',                                             o: 'KS' },
    { m: 'Y',             n: VOWEL,                       o: 'Y'  },
    { m: 'Y',                                             o: '-'  },
    { m: 'Z',                                             o: 'S'  },
  ],
});
