import 'mocha';
import { expect }        from 'chai';
import indefiniteArticle from '../src/indefiniteArticle';

describe(
    'indefiniteArticle',
    () => {
        it(
            'should add select the proper indefinite article',
            () => {
                expect(indefiniteArticle('boy')).to.equal('a boy');
                expect(indefiniteArticle('apple')).to.equal('an apple');
                expect(indefiniteArticle('helicopter')).to.equal('a helicopter');
                expect(indefiniteArticle('elephant')).to.equal('an elephant');
                expect(indefiniteArticle('big elephant')).to.equal('a big elephant');
                expect(indefiniteArticle('itchy sweater')).to.equal('an itchy sweater');
                expect(indefiniteArticle('ugly duck')).to.equal('an ugly duck');
                expect(indefiniteArticle('european')).to.equal('a european');
                expect(indefiniteArticle('university')).to.equal('a university');
                expect(indefiniteArticle('unit')).to.equal('a unit');
                expect(indefiniteArticle('hour')).to.equal('an hour');
                expect(indefiniteArticle('honor')).to.equal('an honor');
                expect(indefiniteArticle('Ath')).to.equal('an Ath');
                expect(indefiniteArticle('Bth')).to.equal('a Bth');
                expect(indefiniteArticle('Cth')).to.equal('a Cth');
                expect(indefiniteArticle('Dth')).to.equal('a Dth');
                expect(indefiniteArticle('Eth')).to.equal('an Eth');
                expect(indefiniteArticle('Fth')).to.equal('an Fth');
                expect(indefiniteArticle('Gth')).to.equal('a Gth');
                expect(indefiniteArticle('Hth')).to.equal('an Hth');
                expect(indefiniteArticle('Ith')).to.equal('an Ith');
                expect(indefiniteArticle('Jth')).to.equal('a Jth');
                expect(indefiniteArticle('Kth')).to.equal('a Kth');
                expect(indefiniteArticle('Lth')).to.equal('an Lth');
                expect(indefiniteArticle('Mth')).to.equal('an Mth');
                expect(indefiniteArticle('Nth')).to.equal('an Nth');
                expect(indefiniteArticle('Oth')).to.equal('an Oth');
                expect(indefiniteArticle('Pth')).to.equal('a Pth');
                expect(indefiniteArticle('Qth')).to.equal('a Qth');
                expect(indefiniteArticle('Rth')).to.equal('an Rth');
                expect(indefiniteArticle('Sth')).to.equal('an Sth');
                expect(indefiniteArticle('Tth')).to.equal('a Tth');
                expect(indefiniteArticle('Uth')).to.equal('a Uth');
                expect(indefiniteArticle('Vth')).to.equal('a Vth');
                expect(indefiniteArticle('Wth')).to.equal('a Wth');
                expect(indefiniteArticle('Xth')).to.equal('an Xth');
                expect(indefiniteArticle('Yth')).to.equal('a Yth');
                expect(indefiniteArticle('Zth')).to.equal('a Zth');
                expect(indefiniteArticle('a-th')).to.equal('an a-th');
                expect(indefiniteArticle('b-th')).to.equal('a b-th');
                expect(indefiniteArticle('c-th')).to.equal('a c-th');
                expect(indefiniteArticle('d-th')).to.equal('a d-th');
                expect(indefiniteArticle('e-th')).to.equal('an e-th');
                expect(indefiniteArticle('f-th')).to.equal('an f-th');
                expect(indefiniteArticle('g-th')).to.equal('a g-th');
                expect(indefiniteArticle('h-th')).to.equal('an h-th');
                expect(indefiniteArticle('i-th')).to.equal('an i-th');
                expect(indefiniteArticle('j-th')).to.equal('a j-th');
                expect(indefiniteArticle('k-th')).to.equal('a k-th');
                expect(indefiniteArticle('l-th')).to.equal('an l-th');
                expect(indefiniteArticle('m-th')).to.equal('an m-th');
                expect(indefiniteArticle('n-th')).to.equal('an n-th');
                expect(indefiniteArticle('o-th')).to.equal('an o-th');
                expect(indefiniteArticle('p-th')).to.equal('a p-th');
                expect(indefiniteArticle('q-th')).to.equal('a q-th');
                expect(indefiniteArticle('r-th')).to.equal('an r-th');
                expect(indefiniteArticle('s-th')).to.equal('an s-th');
                expect(indefiniteArticle('t-th')).to.equal('a t-th');
                expect(indefiniteArticle('u-th')).to.equal('a u-th');
                expect(indefiniteArticle('v-th')).to.equal('a v-th');
                expect(indefiniteArticle('w-th')).to.equal('a w-th');
                expect(indefiniteArticle('x-th')).to.equal('an x-th');
                expect(indefiniteArticle('y-th')).to.equal('a y-th');
                expect(indefiniteArticle('z-th')).to.equal('a z-th');
                expect(indefiniteArticle('A.B.C')).to.equal('an A.B.C');
                expect(indefiniteArticle('AI')).to.equal('an AI');
                expect(indefiniteArticle('AGE')).to.equal('an AGE');
                expect(indefiniteArticle('agendum')).to.equal('an agendum');
                expect(indefiniteArticle('aide-de-camp')).to.equal('an aide-de-camp');
                expect(indefiniteArticle('albino')).to.equal('an albino');
                expect(indefiniteArticle('B.L.T. sandwich')).to.equal('a B.L.T. sandwich');
                expect(indefiniteArticle('BMW')).to.equal('a BMW');
                expect(indefiniteArticle('BLANK')).to.equal('a BLANK');
                expect(indefiniteArticle('bacterium')).to.equal('a bacterium');
                expect(indefiniteArticle('Burmese restaurant')).to.equal('a Burmese restaurant');
                expect(indefiniteArticle('C.O.')).to.equal('a C.O.');
                expect(indefiniteArticle('CCD')).to.equal('a CCD');
                expect(indefiniteArticle('COLON')).to.equal('a COLON');
                expect(indefiniteArticle('cameo')).to.equal('a cameo');
                expect(indefiniteArticle('CAPITAL')).to.equal('a CAPITAL');
                expect(indefiniteArticle('D.S.M.')).to.equal('a D.S.M.');
                expect(indefiniteArticle('DNR')).to.equal('a DNR');
                expect(indefiniteArticle('DINNER')).to.equal('a DINNER');
                expect(indefiniteArticle('dynamo')).to.equal('a dynamo');
                expect(indefiniteArticle('E.K.G.')).to.equal('an E.K.G.');
                expect(indefiniteArticle('ECG')).to.equal('an ECG');
                expect(indefiniteArticle('EGG')).to.equal('an EGG');
                expect(indefiniteArticle('embryo')).to.equal('an embryo');
                expect(indefiniteArticle('erratum')).to.equal('an erratum');
                expect(indefiniteArticle('eucalyptus')).to.equal('a eucalyptus');
                expect(indefiniteArticle('Euler number')).to.equal('an Euler number');
                expect(indefiniteArticle('eulogy')).to.equal('a eulogy');
                expect(indefiniteArticle('euphemism')).to.equal('a euphemism');
                expect(indefiniteArticle('euphoria')).to.equal('a euphoria');
                expect(indefiniteArticle('ewe')).to.equal('a ewe');
                expect(indefiniteArticle('ewer')).to.equal('a ewer');
                expect(indefiniteArticle('extremum')).to.equal('an extremum');
                expect(indefiniteArticle('eye')).to.equal('an eye');
                expect(indefiniteArticle('F.B.I. agent')).to.equal('an F.B.I. agent');
                expect(indefiniteArticle('FSM')).to.equal('an FSM');
                expect(indefiniteArticle('FACT')).to.equal('a FACT');
                expect(indefiniteArticle('FAQ')).to.equal('a FAQ');
                expect(indefiniteArticle('F.A.Q.')).to.equal('an F.A.Q.');
                expect(indefiniteArticle('fish')).to.equal('a fish');
                expect(indefiniteArticle('G-string')).to.equal('a G-string');
                expect(indefiniteArticle('GSM phone')).to.equal('a GSM phone');
                expect(indefiniteArticle('GOD')).to.equal('a GOD');
                expect(indefiniteArticle('genus')).to.equal('a genus');
                expect(indefiniteArticle('Governor General')).to.equal('a Governor General');
                expect(indefiniteArticle('H-Bomb')).to.equal('an H-Bomb');
                expect(indefiniteArticle('H.M.S Ark Royal')).to.equal('an H.M.S Ark Royal');
                expect(indefiniteArticle('HSL colour space')).to.equal('an HSL colour space');
                expect(indefiniteArticle('HAL 9000')).to.equal('a HAL 9000');
                expect(indefiniteArticle('H.A.L. 9000')).to.equal('an H.A.L. 9000');
                expect(indefiniteArticle('has-been')).to.equal('a has-been');
                expect(indefiniteArticle('height')).to.equal('a height');
                expect(indefiniteArticle('heir')).to.equal('an heir');
                expect(indefiniteArticle('honed blade')).to.equal('a honed blade');
                expect(indefiniteArticle('honest man')).to.equal('an honest man');
                expect(indefiniteArticle('honeymoon')).to.equal('a honeymoon');
                expect(indefiniteArticle('honorarium')).to.equal('an honorarium');
                expect(indefiniteArticle('honorary degree')).to.equal('an honorary degree');
                expect(indefiniteArticle('honoree')).to.equal('an honoree');
                expect(indefiniteArticle('honorific')).to.equal('an honorific');
                expect(indefiniteArticle('Hough transform')).to.equal('a Hough transform');
                expect(indefiniteArticle('hound')).to.equal('a hound');
                expect(indefiniteArticle('hour')).to.equal('an hour');
                expect(indefiniteArticle('hourglass')).to.equal('an hourglass');
                expect(indefiniteArticle('houri')).to.equal('a houri');
                expect(indefiniteArticle('house')).to.equal('a house');
                expect(indefiniteArticle('I.O.U.')).to.equal('an I.O.U.');
                expect(indefiniteArticle('IQ')).to.equal('an IQ');
                expect(indefiniteArticle('IDEA')).to.equal('an IDEA');
                expect(indefiniteArticle('inferno')).to.equal('an inferno');
                expect(indefiniteArticle('Inspector General')).to.equal('an Inspector General');
                expect(indefiniteArticle('jumbo')).to.equal('a jumbo');
                expect(indefiniteArticle('knife')).to.equal('a knife');
                expect(indefiniteArticle('L.E.D.')).to.equal('an L.E.D.');
                expect(indefiniteArticle('LED')).to.equal('a LED');
                expect(indefiniteArticle('LCD')).to.equal('an LCD');
                expect(indefiniteArticle('lady in waiting')).to.equal('a lady in waiting');
                expect(indefiniteArticle('leaf')).to.equal('a leaf');
                expect(indefiniteArticle('M.I.A.')).to.equal('an M.I.A.');
                expect(indefiniteArticle('MIASMA')).to.equal('a MIASMA');
                expect(indefiniteArticle('MTV channel')).to.equal('an MTV channel');
                expect(indefiniteArticle('Major General')).to.equal('a Major General');
                expect(indefiniteArticle('N.C.O.')).to.equal('an N.C.O.');
                expect(indefiniteArticle('NCO')).to.equal('an NCO');
                expect(indefiniteArticle('NATO country')).to.equal('a NATO country');
                expect(indefiniteArticle('note')).to.equal('a note');
                expect(indefiniteArticle('O.K.')).to.equal('an O.K.');
                expect(indefiniteArticle('OK')).to.equal('an OK');
                expect(indefiniteArticle('OLE')).to.equal('an OLE');
                expect(indefiniteArticle('octavo')).to.equal('an octavo');
                expect(indefiniteArticle('octopus')).to.equal('an octopus');
                expect(indefiniteArticle('okay')).to.equal('an okay');
                expect(indefiniteArticle('once-and-future-king')).to.equal('a once-and-future-king');
                expect(indefiniteArticle('oncologist')).to.equal('an oncologist');
                expect(indefiniteArticle('one night stand')).to.equal('a one night stand');
                expect(indefiniteArticle('onerous task')).to.equal('an onerous task');
                expect(indefiniteArticle('opera')).to.equal('an opera');
                expect(indefiniteArticle('optimum')).to.equal('an optimum');
                expect(indefiniteArticle('opus')).to.equal('an opus');
                expect(indefiniteArticle('ox')).to.equal('an ox');
                expect(indefiniteArticle('Ph.D.')).to.equal('a Ph.D.');
                expect(indefiniteArticle('PET')).to.equal('a PET');
                expect(indefiniteArticle('P.E.T. scan')).to.equal('a P.E.T. scan');
                expect(indefiniteArticle('plateau')).to.equal('a plateau');
                expect(indefiniteArticle('quantum')).to.equal('a quantum');
                expect(indefiniteArticle('R.S.V.P.')).to.equal('an R.S.V.P.');
                expect(indefiniteArticle('RSVP')).to.equal('an RSVP');
                expect(indefiniteArticle('REST')).to.equal('a REST');
                expect(indefiniteArticle('reindeer')).to.equal('a reindeer');
                expect(indefiniteArticle('S.O.S.')).to.equal('an S.O.S.');
                expect(indefiniteArticle('SUM')).to.equal('a SUM');
                expect(indefiniteArticle('SST')).to.equal('an SST');
                expect(indefiniteArticle('salmon')).to.equal('a salmon');
                expect(indefiniteArticle('T.N.T. bomb')).to.equal('a T.N.T. bomb');
                expect(indefiniteArticle('TNT bomb')).to.equal('a TNT bomb');
                expect(indefiniteArticle('TENT')).to.equal('a TENT');
                expect(indefiniteArticle('thought')).to.equal('a thought');
                expect(indefiniteArticle('tomato')).to.equal('a tomato');
                expect(indefiniteArticle('U-boat')).to.equal('a U-boat');
                expect(indefiniteArticle('UNESCO representative')).to.equal('a UNESCO representative');
                expect(indefiniteArticle('U.F.O.')).to.equal('a U.F.O.');
                expect(indefiniteArticle('UFO')).to.equal('a UFO');
                expect(indefiniteArticle('UK citizen')).to.equal('a UK citizen');
                expect(indefiniteArticle('ubiquity')).to.equal('a ubiquity');
                expect(indefiniteArticle('unicorn')).to.equal('a unicorn');
                expect(indefiniteArticle('unidentified flying object')).to.equal('an unidentified flying object');
                expect(indefiniteArticle('uniform')).to.equal('a uniform');
                expect(indefiniteArticle('unimodal system')).to.equal('a unimodal system');
                expect(indefiniteArticle('unimpressive record')).to.equal('an unimpressive record');
                expect(indefiniteArticle('uninformed opinion')).to.equal('an uninformed opinion');
                expect(indefiniteArticle('uninvited guest')).to.equal('an uninvited guest');
                expect(indefiniteArticle('union')).to.equal('a union');
                expect(indefiniteArticle('uniplex')).to.equal('a uniplex');
                expect(indefiniteArticle('uniprocessor')).to.equal('a uniprocessor');
                expect(indefiniteArticle('unique opportunity')).to.equal('a unique opportunity');
                expect(indefiniteArticle('unisex hairdresser')).to.equal('a unisex hairdresser');
                expect(indefiniteArticle('unison')).to.equal('a unison');
                expect(indefiniteArticle('unit')).to.equal('a unit');
                expect(indefiniteArticle('unitarian')).to.equal('a unitarian');
                expect(indefiniteArticle('united front')).to.equal('a united front');
                expect(indefiniteArticle('unity')).to.equal('a unity');
                expect(indefiniteArticle('univalent bond')).to.equal('a univalent bond');
                expect(indefiniteArticle('univariate statistic')).to.equal('a univariate statistic');
                expect(indefiniteArticle('universe')).to.equal('a universe');
                expect(indefiniteArticle('unordered meal')).to.equal('an unordered meal');
                expect(indefiniteArticle('uranium atom')).to.equal('a uranium atom');
                expect(indefiniteArticle('urban myth')).to.equal('an urban myth');
                expect(indefiniteArticle('urbane miss')).to.equal('an urbane miss');
                expect(indefiniteArticle('urchin')).to.equal('an urchin');
                expect(indefiniteArticle('urea detector')).to.equal('a urea detector');
                expect(indefiniteArticle('urethane monomer')).to.equal('a urethane monomer');
                expect(indefiniteArticle('urge')).to.equal('an urge');
                expect(indefiniteArticle('urgency')).to.equal('an urgency');
                expect(indefiniteArticle('urinal')).to.equal('a urinal');
                expect(indefiniteArticle('urn')).to.equal('an urn');
                expect(indefiniteArticle('usage')).to.equal('a usage');
                expect(indefiniteArticle('use')).to.equal('a use');
                expect(indefiniteArticle('usher')).to.equal('an usher');
                expect(indefiniteArticle('usual suspect')).to.equal('a usual suspect');
                expect(indefiniteArticle('usurer')).to.equal('a usurer');
                expect(indefiniteArticle('usurper')).to.equal('a usurper');
                expect(indefiniteArticle('utensil')).to.equal('a utensil');
                expect(indefiniteArticle('utility')).to.equal('a utility');
                expect(indefiniteArticle('utmost urgency')).to.equal('an utmost urgency');
                expect(indefiniteArticle('utopia')).to.equal('a utopia');
                expect(indefiniteArticle('utterance')).to.equal('an utterance');
                expect(indefiniteArticle('V.I.P.')).to.equal('a V.I.P.');
                expect(indefiniteArticle('VIPER')).to.equal('a VIPER');
                expect(indefiniteArticle('viper')).to.equal('a viper');
                expect(indefiniteArticle('X-ray')).to.equal('an X-ray');
                expect(indefiniteArticle('X.O.')).to.equal('an X.O.');
                expect(indefiniteArticle('XYLAPHONE')).to.equal('a XYLAPHONE');
                expect(indefiniteArticle('XY chromosome')).to.equal('an XY chromosome');
                expect(indefiniteArticle('xenophobe')).to.equal('a xenophobe');
                expect(indefiniteArticle('Y-shaped pipe')).to.equal('a Y-shaped pipe');
                expect(indefiniteArticle('Y.Z. plane')).to.equal('a Y.Z. plane');
                expect(indefiniteArticle('YMCA')).to.equal('a YMCA');
                expect(indefiniteArticle('YBLENT eye')).to.equal('an YBLENT eye');
                expect(indefiniteArticle('yblent eye')).to.equal('an yblent eye');
                expect(indefiniteArticle('yclad body')).to.equal('an yclad body');
                expect(indefiniteArticle('yellowing')).to.equal('a yellowing');
                expect(indefiniteArticle('yield')).to.equal('a yield');
                expect(indefiniteArticle('youth')).to.equal('a youth');
                expect(indefiniteArticle('youth')).to.equal('a youth');
                expect(indefiniteArticle('ypsiliform junction')).to.equal('an ypsiliform junction');
                expect(indefiniteArticle('yttrium atom')).to.equal('an yttrium atom');
                expect(indefiniteArticle('zoo')).to.equal('a zoo');
            }
        );

        it(
            'should support the only option',
            () => {
                expect(indefiniteArticle('boy', { only: true })).to.equal('a');
                expect(indefiniteArticle('apple', { only: true })).to.equal('an');
            }
        );

        it(
            'should should work with made up words',
            () => {
                expect(indefiniteArticle('aqk')).to.equal('an aqk');
                expect(indefiniteArticle('qka')).to.equal('a qka');
            }
        );
    }
);

