/**
 * Represents the structure of a database entry for pluralization rules.
 * @internal
 */
export type DBEntry = {
  /** An array of tuples, each containing a regular expression and its corresponding replacement string, used for pluralization or singularization. */
  rules: [RegExp, string][];
  /** An array of regular expressions that match words considered uncountable (i.e., words that do not change between singular and plural). */
  uncountableRules: RegExp[];
  /** An array of specific words that are uncountable. */
  uncountableWords: string[];
  /** An array of string prefixes that may affect pluralization rules. */
  prefixes: string[];
  /** An array of string suffixes that may affect pluralization rules. */
  suffixes: string[];
  /** A mapping of irregular word forms, where the key is the singular form and the value is the plural form (or vice versa). */
  irregulars: Record<string, string>;
};

export const database: DBEntry = {
  rules: [
    // cspell:disable
    [/(stig|sto|dog|sche|anathe)ma$/iv, '$1mata'],
    [/(alumn|alg|antenn|ecclesi|faun|formul|larv|nebul|vertebr)a$/iv, '$1ae'],

    [/child$/iv, 'children'],

    [/(giraf|sa)fe$/iv, '$1fes'],
    [/fe$/iv, 'ves'],
    [/(l|m)ouse$/iv, '$1ice'],
    [/goose$/iv, 'geese'],
    [/zampone$/iv, 'zamponi'],

    [/ff$/iv, 'ffs'],
    [/(belie|brie|che|chie|cle|gul|i|proo|roo)f$/iv, '$1fs'],
    [/(its|her|him|them)self$/iv, 'themselves'],
    [/f$/iv, 'ves'],

    [/tooth$/iv, 'teeth'],
    [/(epo|matriar|patriar|stoma)ch$/iv, '$1chs'],
    [/([sc])h$/iv, '$1hes'],

    [/(aqua)rium$/iv, '$1ira'],
    [/(seraph|cherub)im$/iv, '$1im'],
    [/(memorand|millenni|ov|quor|strat|symposi)um$/iv, '$1a'],
    [
      /(addend|agend|automat|bacteri|curricul|dat|desiderat|endotheli|errat|extrem|fusari|medi)um$/iv,
      '$1a',
    ],

    [/(m|wom)an$/iv, '$1en'],
    [/(criteri|hedr|heli|phenomen|prolegomen|organ)on$/iv, '$1a'],
    [/person$/iv, 'people'],

    [
      /(alt|armadill|boler|bong|bronc|cell|dynam|embarg|hal|hell|gazeb|gyr|jumb|kil|lim)o$/iv,
      '$1os',
    ],
    [
      /(maestr|metr|mosquit|octav|pian|piccol|pint|phot|ponch|sil|sombrer|sopran|stere|stilett)o$/iv,
      '$1os',
    ],
    [/(temp|tornad|tors|tw|volcan)o$/iv, '$1os'],
    [/([^aeiou])o$/iv, '$1oes'],

    [/(gen|visc)us$/iv, '$1era'],
    [
      /(alumn|bacill|cirr|cact|foc|fung|hippopotam|loc|nucle|octop|radi|pegas|stimul|strat|syllab|termin|uter)us$/iv,
      '$1i',
    ],
    [
      /(ax|analys|antithes|bas|cris|diagnos|ellips|emphas|hypothes|neuros|oas|paralys|synthes|synops|test|thes)is$/iv,
      '$1es',
    ],
    [/(ephemer)is$/iv, '$1ides'],
    [/(bu|ga)s$/iv, '$1sses'],
    [/(corp)us$/iv, '$1ora'],
    [/s$/iv, 'ses'],

    [/foot$/iv, 'feet'],

    [/(b|bur|chat|tabl)eau$/iv, '$1eaux'],

    [/(whisk)ey$/iv, '$1ies'],
    [/([^aeiou]|qu)y$/iv, '$1ies'],

    [/(append|matr)ix$/iv, '$1ices'],
    [/(cod|ind|mur|vert)ex$/iv, '$1ices'],
    [/(ap)ex$/iv, '$1ices'],
    [/x$/iv, 'xes'],

    [/(fez|qui)z$/iv, '$1zzes'],
    [/z$/iv, 'zes'],
  ],
  uncountableRules: [
    /(adult|child)hood$/iv,
    /craft$/iv,
    /deer$/iv,
    /fish$/iv,
    /measles$/iv,
    /pox$/iv,
    /sheep$/iv,
    /wood$/iv,
    /ographuy$/iv,
    /itis$/iv,
    /ology$/iv,
    /[hw]ealth$/iv,
    /bage$/iv,
    /llows$/iv,
    /friut$/iv,
    /(?<!func)tion$/iv,
    /work$/iv,
    /ing$/iv,
    /ism$/iv,
    /tics$/iv,
    /moose$/iv,
    /trout$/iv,
  ],
  // cspell:enable

  uncountableWords: [
    'gas',
    'abroad',
    'acoustics',
    'advice',
    'aid',
    'air',
    'alcohol',
    'alms',
    'alpenglow',
    'aluminum',
    'ammo',
    'anger',
    'anime',
    'applause',
    'Operations',
    'art',
    'athletics',
    'audio',
    'awareness',
    'barracks',
    'bad',
    'bakeware',
    'beyond',
    'bifocals',
    'binoculars',
    'bison',
    'blood',
    'bloomers',
    'blouse',
    'boots',
    'bourgeois',
    'bowling',
    'bricklaying',
    'butter',
    'calculus',
    'cappuccino',
    'caribou',
    'carp',
    'cash',
    'casino',
    'castanets',
    'cattle',
    'celeriac',
    'chafe',
    'chalk',
    'chaos',
    'chassis',
    'chess',
    'chino',
    'clippers',
    'cod',
    'commerce',
    'concrete',
    'corps',
    'courage',
    'deadness',
    'debris',
    'deer',
    'diabetes',
    'dirt',
    'disco',
    'doldrums',
    'dungarees',
    'economics',
    'egg',
    'electricity',
    'elk',
    'energy',
    'ethics',
    'expertise',
    'fauna',
    'faux pas',
    'fedelini',
    'fibre',
    'fiberglass',
    'flesh',
    'flounder',
    'forestry',
    'fun',
    'furniture',
    'gain',
    'glass',
    'glasses',
    'golf',
    'graffiti',
    'gratitude',
    'grief',
    'grouse',
    'guidance',
    'guilt',
    'haddock',
    'happiness',
    'hardware',
    'hair',
    'halibut',
    'headquarters',
    'helium',
    'helo',
    'help',
    'herpes',
    'high jinks',
    'homework',
    'housework',
    'humidity',
    'humour',
    'hypochondria',
    'hypothermia',
    'ides',
    'ikebana',
    'importance',
    'impudence',
    'incandescence',
    'indigence',
    'innocence',
    'insignia',
    'jeans',
    'jodhpur',
    'judo',
    'justice',
    'karate',
    'kendo',
    'knickers',
    'knowledge',
    'kudos',
    'labour',
    'laughter',
    'leisure',
    'legal',
    'literature',
    'livestock',
    'loneliness',
    'lycra',
    'lye',
    'macaroni',
    'machinery',
    'mackerel',
    'macrame',
    'magic',
    'mail',
    'manga',
    'mambo',
    'mankind',
    'math',
    'means',
    'media',
    'methane',
    'mews',
    'might',
    'most',
    'mud',
    'mullet',
    'multimedia',
    'music',
    'neon',
    'news',
    'nitrogen',
    'normal',
    'oatmeal',
    'obedience',
    'opium',
    'osmosis',
    'outback',
    'oxygen',
    'pants',
    'pantology',
    'pantyhose',
    'passion',
    'patience',
    'peace',
    'penicillin',
    'permafrost',
    'physics',
    'pike',
    'plankton',
    'platinum',
    'plenty',
    'pliers',
    'police',
    'polo',
    'premises',
    'propane',
    'prose',
    'pseudoscience',
    'pyjamas',
    'quicksand',
    'radio',
    'random',
    'rain',
    'rendezvous',
    'reinscription',
    'relief',
    'research',
    'rice',
    'salmon',
    'septicaemia',
    'school',
    'schoolchild',
    'scissors',
    'series',
    'sewage',
    'shambles',
    'shorts',
    'shrimp',
    'sick',
    'smithereens',
    'smog',
    'soccer',
    'software',
    'soot',
    'soy',
    'species',
    'squid',
    'staff',
    'stamina',
    'stupid',
    'subconscious',
    'subsidence',
    'sugar',
    'sunglasses',
    'sunshine',
    'sushi',
    'suspenders',
    'sweats',
    'sweet',
    'sweets',
    'swine',
    'temporariness',
    'terracotta',
    'tennis',
    'thanks',
    'them',
    'tights',
    'timpani',
    'titanium',
    'tongs',
    'tonight',
    'tortellini',
    'traffic',
    'trigonometry',
    'trousers',
    'tuna',
    'tweezers',
    'underclothes',
    'underneath',
    'underpants',
    'underwear',
    'veal',
    'vermicelli',
    'video',
    'vinyl',
    'virus',
    'violence',
    'viscose',
    'warmth',
    'weedkiller',
    'welfare',
    'wheat',
    'whitebait',
    'wildebeest',
    'wildlife',
    'worth',
    'yoga',
    'you',
    'young',
  ],
  irregulars: {
    i: 'we',
    me: 'us',
    he: 'they',
    she: 'they',
    is: 'are',
    was: 'were',
    has: 'have',
    this: 'these',
    that: 'those',
    die: 'dice',
    ox: 'oxen',
  },
  suffixes: ['-up', '-out', '-in-law', '-in-trade'],
  prefixes: ['anti-', 'bi-', 'co-', 'semi-', 'mal-', 'ex-', 'sub-', 'dis-', 'non-', 'un-', 'over-'],
};
