import { type DBEntry } from './pluralization.ts';

export const database: DBEntry = {
  rules: [
    [/us$/iv, 'i'],
    [/is$/iv, 'es'],
    [/on$/iv, 'a'],
    [/(s|ss|sh|ch|x|z)$/iv, 'es'],
    [/([^aeiou])y$/iv, '$1ies'],
    [/fe?$/iv, 'ves'],
    [/([^aeiou])o$/iv, '$1oes'],
  ],
  uncountableRules: [],
  uncountableWords: [
    'sheep',
    'fish',
    'deer',
    'moose',
    'series',
    'species',
    'money',
    'rice',
    'information',
    'equipment',
    'bison',
    'cod',
    'offspring',
    'pike',
    'salmon',
    'shrimp',
    'swine',
    'trout',
    'craft',
    'sugar',
    'tuna',
    'you',
    'wood',
    'police',
  ],
  irregulars: {
    man: 'men',
    child: 'children',
    tooth: 'teeth',
    foot: 'feet',
    goose: 'geese',
    mouse: 'mice',
    ox: 'oxen',
    person: 'people',
    die: 'dice',
  },
  prefixes: [],
  suffixes: [],
};
